import type OgaAvatar from "./avatar/src/index.vue";
import type OgaEditor from "./editor/src/index.vue";
import type OgaForm from "./form/src/index.vue";
import type OgaFormItem from "./form-item/src/index.vue";
import type OgaIcon from "./iconfont/src/index.vue";
import type OgaImageUpload from "./image-upload/src/index.vue";
import type OgaInput from "./input/src/index.vue";
import type OgaInputNumber from "./input/src/input-number.vue";
import type OgaInputTag from "./input/src/tag.vue";
import type OgaCascader from "./input/src/cascader.vue";
import type OgaDatePicker from "./input/src/date-picker.vue";
import type OgaMention from "./input/src/mention.vue";
import type OgaSelect from "./input/src/select.vue";
import type OgaSelectV2 from "./input/src/select-v2.vue";
import type OgaTimePicker from "./input/src/time-picker.vue";
import type OgaTimeSelect from "./input/src/time-select.vue";
import type OgaTreeSelect from "./input/src/tree-select.vue";
import type ElIcon from "./icon/src/index.vue";
import type OgaPage from "./page/src/index.vue";
import type OgaPaging from "./paging/src/index.vue";
import type OgaSection from "./section/src/index.vue";
import type OgaTable from "./table/src/index.vue";
import type OgaUnsaved from "./unsaved/src/index.vue";

declare module "vue" {
  export interface GlobalComponents {
    OgaAvatar: typeof OgaAvatar;
    "oga-avatar": typeof OgaAvatar;
    OgaEditor: typeof OgaEditor;
    "oga-editor": typeof OgaEditor;
    OgaForm: typeof OgaForm;
    "oga-form": typeof OgaForm;
    OgaFormItem: typeof OgaFormItem;
    "oga-form-item": typeof OgaFormItem;
    OgaIcon: typeof OgaIcon;
    "oga-icon": typeof OgaIcon;
    OgaImageUpload: typeof OgaImageUpload;
    "oga-image-upload": typeof OgaImageUpload;
    OgaInput: typeof OgaInput;
    "oga-input": typeof OgaInput;
    OgaInputNumber: typeof OgaInputNumber;
    "oga-input-number": typeof OgaInputNumber;
    OgaInputTag: typeof OgaInputTag;
    "oga-input-tag": typeof OgaInputTag;
    OgaCascader: typeof OgaCascader;
    "oga-cascader": typeof OgaCascader;
    OgaDatePicker: typeof OgaDatePicker;
    "oga-date-picker": typeof OgaDatePicker;
    OgaMention: typeof OgaMention;
    "oga-mention": typeof OgaMention;
    OgaSelect: typeof OgaSelect;
    "oga-select": typeof OgaSelect;
    OgaSelectV2: typeof OgaSelectV2;
    "oga-select-v2": typeof OgaSelectV2;
    OgaTimePicker: typeof OgaTimePicker;
    "oga-time-picker": typeof OgaTimePicker;
    OgaTimeSelect: typeof OgaTimeSelect;
    "oga-time-select": typeof OgaTimeSelect;
    OgaTreeSelect: typeof OgaTreeSelect;
    "oga-tree-select": typeof OgaTreeSelect;
    OgaPage: typeof OgaPage;
    "oga-page": typeof OgaPage;
    OgaPaging: typeof OgaPaging;
    "oga-paging": typeof OgaPaging;
    OgaSection: typeof OgaSection;
    "oga-section": typeof OgaSection;
    OgaTable: typeof OgaTable;
    "oga-table": typeof OgaTable;
    OgaUnsaved: typeof OgaUnsaved;
    "oga-unsaved": typeof OgaUnsaved;
    ElIcon: typeof ElIcon;
    "el-icon": typeof ElIcon;
  }
}
